name: 'Publish HeroHQ'

on:
  push:
    branches:
      - master

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7.15.0
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Dependencies and Build App
        run: pnpm i
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: hero-hq-v__VERSION__
          releaseName: 'HeroHQ v__VERSION__'
          releaseBody: 'Download the MSI to get started'
          releaseDraft: true
          prerelease: false
